"""Phase 3 of the preview cache eviction plan: AI-worker resilience under miss.

Previews are disposable: the LRU evictor (Phase 2) or a wiped cache volume can
remove a set that Postgres still records as ``ready``. The AI pipeline must
therefore regenerate its own preview on a cache miss instead of hard-failing,
and a reuse candidate whose preview is no longer cached must simply be skipped
(degrading to a full analysis) rather than fail the job.

The VLM, the Ollama digest lookup, and the face detector are stubbed (no
Ollama or AI-worker service is started); the miss paths run real
``worker.generate()`` / fingerprint / candidate / publish code against a
disposable Postgres catalog, S3 bucket, and scratch directory. One further
test (Phase 2B) drives the real ``RemoteFaceAnalyzer`` against an in-process
stub HTTP server implementing the face-service contract — still without any
external service.

Phase 3A adds the service gate to every test here: both service URLs are
stub-configured and both probes stubbed healthy, so the worker claims
exactly as before. The gate's own behavior (unconfigured idle, probe-blocked
claims, requeue on a mid-job outage, the bounded dispatcher) is covered by
the ``test_unconfigured_*`` / ``test_gate_*`` / ``test_face_outage_*`` /
``test_vlm_request_error_*`` / ``test_dispatcher_*`` tests at the end of the
file, using the stub HTTP server and no external service.
"""

import json
import shutil
import threading
from dataclasses import dataclass
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from uuid import uuid4

from PIL import Image, ImageDraw
from sqlalchemy import text
from test_integration import backend as backend  # noqa: F401
from test_integration import pytestmark  # noqa: F401

import photo_server.ai_worker as ai_worker
from photo_server.ai_worker import AIWorker
from photo_server.analysis import PIPELINE_VERSION, AIRequestError, SemanticAnalysis
from photo_server.face_client import ADAFACE_IDENTITY, RemoteFaceAnalyzer
from photo_server.fingerprints import BURST_HASH_VERSION
from photo_server.models import Blob, Manifest
from photo_server.worker import cache_paths, generate

DIGEST = "abc123def456"
CAMERA = {"Make": "Canon", "Model": "EOS R5"}
CAPTURE_A = "2026-01-01T12:00:00+00:00"  # source frame of a burst
CAPTURE_B = "2026-01-01T12:00:01+00:00"  # target: 1 s later, inside the window
FAKE_SEMANTIC = SemanticAnalysis(
    summary="A quiet outdoor scene.",
    photo_types=["landscape"],
    scene="outdoors",
    setting="outdoor",
)


class FaceStub:
    model_version = "stub"

    def analyze(self, jpeg) -> list[dict]:
        return [{"box": [0.1, 0.1, 0.2, 0.2], "confidence": 0.9, "embedding": [1.0, 0.0]}]


def make_worker(backend, monkeypatch, calls: list):
    # Phase 3A gate: both service URLs stub-configured (non-empty) and both
    # probes stubbed healthy, so the worker claims exactly as before the gate
    # existed.
    backend.service.settings = backend.service.settings.model_copy(
        update={"ai_base_url": "http://vlm-stub/v1", "face_service_url": "http://face-stub/"}
    )
    worker = AIWorker(backend.service)
    worker._faces = FaceStub()
    monkeypatch.setattr(worker, "_probe_vlm", lambda: True)
    monkeypatch.setattr(worker, "_probe_face", lambda: True)

    def fake_analyze_semantics(settings, jpeg):
        calls[0] += 1
        return FAKE_SEMANTIC, DIGEST, {}

    monkeypatch.setattr(ai_worker, "analyze_semantics", fake_analyze_semantics)
    monkeypatch.setattr(ai_worker, "resolve_model_digest", lambda settings, model: DIGEST)
    return worker


# --- A near-duplicate pair, PIL-generated (no external assets). --------------


def base_image() -> Image.Image:
    width, height = 640, 480
    img = Image.new("L", (width, height))
    img.putdata([40 + int(180 * x / (width - 1)) for _ in range(height) for x in range(width)])
    ImageDraw.Draw(img).rectangle([120, 120, 300, 380], fill=250)
    return img


def shifted_image() -> Image.Image:
    # A uniform +2 brightness shift keeps pHash/dHash identical and the pixel
    # similarity comfortably above the 0.95 reuse gate.
    return base_image().point(lambda p: min(255, p + 2))


def apply_manifest(backend, name, capture_time, metadata) -> str:
    """Apply a manifest and put a 1x1-ish real JPEG in S3 for the blob, so a
    preview can be generated (and later regenerated by real code) from it."""
    asset_id = uuid4()
    blob_id = uuid4()
    blob = Blob(
        blob_id=blob_id,
        role="ORIGINAL_JPEG",
        original_filename=name,
        object_key=f"originals/{asset_id}/{name}",
        sha256=uuid4().hex + uuid4().hex,
        size_bytes=100,
        mime_type="image/jpeg",
    )
    manifest = Manifest(
        library_id=backend.service.library_id,
        asset_id=asset_id,
        operation_id=uuid4(),
        primary_blob_id=blob_id,
        blobs=[blob],
        imported_at="2026-01-01T00:00:00+00:00",
        capture_time=capture_time,
        metadata=metadata,
    )
    backend.service.catalog.apply(manifest)
    original = backend.root / name
    Image.new("RGB", (800, 600)).save(original, format="JPEG")
    backend.service.storage.put(blob.object_key, original.read_bytes(), "image/jpeg")
    return str(asset_id)


def add_plain_asset(backend, name) -> str:
    """A plain manifest (no capture time: never a reuse candidate)."""
    return apply_manifest(backend, name, None, {})


def add_pair_asset(backend, name, capture_time) -> str:
    """A burst-style manifest: capture time plus camera metadata."""
    return apply_manifest(backend, name, capture_time, CAMERA)


def park_ai_job(backend, asset_id: str) -> None:
    """Retire the asset's ai-v1 job; the worker must not claim it."""
    backend.service.catalog.finish_processing_job(asset_id, "ai-v1", "ready")


def make_preview(backend, asset_id: str) -> None:
    """Generate the real preview files and mark the preview job ready."""
    manifest = backend.service.catalog.get(asset_id)
    assert generate(backend.service, manifest) is True
    assert all(path.exists() for path in cache_paths(backend.service, manifest).values())
    backend.service.catalog.finish_processing_job(asset_id, "preview-v1", "ready")


def store_preview(backend, asset_id: str, image: Image.Image) -> None:
    """Use a specific PIL image as the asset's preview (its exact hash is the
    test's control over pHash/dHash), then mark the preview job ready."""
    paths = cache_paths(backend.service, backend.service.catalog.get(asset_id))
    paths["preview"].parent.mkdir(parents=True, exist_ok=True)
    image.save(paths["preview"], format="JPEG")
    backend.service.catalog.finish_processing_job(asset_id, "preview-v1", "ready")


def wipe_cache_dir(backend, asset_id: str):
    """Delete exactly this asset's cache directory (an eviction-shaped miss)."""
    manifest = backend.service.catalog.get(asset_id)
    shutil.rmtree(cache_paths(backend.service, manifest)["preview"].parent, ignore_errors=True)
    assert not cache_paths(backend.service, manifest)["preview"].exists()


def job_error(backend, asset_id: str) -> str | None:
    with backend.service.catalog.engine.connect() as connection:
        return connection.scalar(
            text("SELECT error FROM jobs WHERE asset_id = :a AND job_type = 'ai-v1'"),
            {"a": asset_id},
        )


def test_missing_preview_is_regenerated_and_job_proceeds(backend, monkeypatch):
    """Ready status + missing file + successful regeneration -> the job succeeds.

    This is the plan's Phase 3 validation line: the AI job must proceed as if
    the preview had been cached the whole time.
    """
    calls = [0]
    worker = make_worker(backend, monkeypatch, calls)
    asset_id = add_plain_asset(backend, "regen-target.JPG")
    make_preview(backend, asset_id)
    wipe_cache_dir(backend, asset_id)
    # The preview job still says ready; only the files are gone.
    assert backend.service.catalog.preview_status(asset_id)["status"] == "ready"
    assert job_error(backend, asset_id) is None

    result = worker.run_once()
    assert result["status"] == "ready", result
    assert result.get("previewRegenerated") is True
    assert result["semanticOrigin"] == "computed"
    assert calls[0] == 1

    # The real files came back, the set is tracked again, and no error was
    # recorded anywhere.
    manifest = backend.service.catalog.get(asset_id)
    assert all(path.is_file() for path in cache_paths(backend.service, manifest).values())
    assert backend.service.catalog.preview_status(asset_id)["status"] == "ready"
    assert job_error(backend, asset_id) is None
    with backend.service.catalog.engine.connect() as connection:
        row = connection.execute(
            text("SELECT asset_id FROM preview_cache WHERE asset_id = :a"), {"a": asset_id}
        ).one()
    assert row is not None


def test_missing_preview_regeneration_failure_is_unavailable(backend, monkeypatch):
    """Ready status + missing file + failed regeneration -> the preview-unavailable
    path is taken instead of the old 'ready but missing' hard failure."""
    calls = [0]
    worker = make_worker(backend, monkeypatch, calls)
    asset_id = add_plain_asset(backend, "regen-fail.JPG")
    make_preview(backend, asset_id)
    wipe_cache_dir(backend, asset_id)

    def fail_generate(service, manifest):
        return False

    with monkeypatch.context() as m:
        m.setattr(ai_worker, "generate", fail_generate)
        result = worker.run_once()

    assert result["status"] == "failed", result
    assert "regeneration is unavailable" in result["error"]
    assert "cache file is missing" not in result["error"]
    assert result["stage"] == "setup"
    # The preview job is left in the state the preview pipeline records for an
    # asset whose preview cannot be produced, so the UI sees a 404, not a 500.
    assert backend.service.catalog.preview_status(asset_id)["status"] == "unavailable"
    assert calls[0] == 0
    assert "regeneration is unavailable" in (job_error(backend, asset_id) or "")
    # And the job's own row is failed, not stuck as running.
    with backend.service.catalog.engine.connect() as connection:
        status = connection.scalar(
            text(
                "SELECT status FROM jobs WHERE asset_id = :a AND job_type = 'ai-v1'"
            ),
            {"a": asset_id},
        )
    assert status == "failed"


def test_no_regeneration_when_preview_exists(backend, monkeypatch):
    """A healthy cache file never triggers the regeneration path."""
    calls = [0]
    worker = make_worker(backend, monkeypatch, calls)
    asset_id = add_plain_asset(backend, "regen-untouched.JPG")
    make_preview(backend, asset_id)
    original_bytes = cache_paths(backend.service, backend.service.catalog.get(asset_id))[
        "preview"
    ].read_bytes()

    def no_regenerate(*args, **kwargs):
        raise AssertionError("generate() must not be called when the preview file exists")

    monkeypatch.setattr(ai_worker, "generate", no_regenerate)
    result = worker.run_once()
    assert result["status"] == "ready", result
    assert result.get("previewRegenerated") is None
    assert calls[0] == 1
    # The preview file was read as-is (no rewrite, no regeneration).
    assert (
        cache_paths(backend.service, backend.service.catalog.get(asset_id))["preview"].read_bytes()
        == original_bytes
    )


def test_regenerated_preview_survives_evict_requeue_roundtrip(backend, monkeypatch):
    """Wipe the whole cache (volume-wipe shape) and requeue: the job succeeds.

    This is the Phase 3 definition of done: ``rm -rf {data_dir}/cache`` + a
    requeued ``ai-v1`` job regenerates its preview and completes.
    """
    calls = [0]
    worker = make_worker(backend, monkeypatch, calls)
    service = backend.service
    asset_id = add_plain_asset(backend, "wipe-roundtrip.JPG")
    make_preview(backend, asset_id)

    shutil.rmtree(service.settings.data_dir / "cache", ignore_errors=True)
    service.catalog.queue_ai([asset_id])
    result = worker.run_once()

    assert result["status"] == "ready", result
    assert result.get("previewRegenerated") is True
    assert calls[0] == 1
    regenerated = cache_paths(service, service.catalog.get(asset_id))
    assert all(path.is_file() for path in regenerated.values())
    # The regenerated set was re-tracked for future eviction decisions.
    with service.catalog.engine.connect() as connection:
        row = connection.execute(
            text(
                "SELECT preview_bytes, thumbnail_bytes FROM preview_cache "
                "WHERE asset_id = :a"
            ),
            {"a": asset_id},
        ).one()
    assert row[0] > 0 and row[1] > 0


def test_reuse_candidate_with_missing_preview_is_skipped(backend, monkeypatch, capsys):
    """A candidate whose preview is not cached is skipped (logged) instead of
    risking an incorrect similarity, degrading the target to a full analysis.

    The source is a verified near-duplicate of the target (same camera, 1 s
    apart, identical previews before the evict) that a real ``run_once`` fully
    analyzed -- the fingerprint it persisted is what makes the *real* candidate
    query return it. Its preview is then evicted, and the target's analysis
    must find the candidate via the production path but skip it at the cache
    miss, log the skip, and fall back to the VLM without failing.
    """
    service = backend.service
    source_id = add_pair_asset(backend, "reuse-src-miss.JPG", CAPTURE_A)
    store_preview(backend, source_id, base_image())
    target_id = add_pair_asset(backend, "reuse-tgt-miss.JPG", CAPTURE_B)
    # The target's fresh import queued its own ai-v1 job; park it so the run
    # below claims the source, then requeue it before the target's own run.
    park_ai_job(backend, target_id)
    store_preview(backend, target_id, base_image())

    # The source completes a normal analysis: fingerprint persisted, run ready,
    # ai-v1 job retired by its own completion.
    source_calls = [0]
    source_result = make_worker(backend, monkeypatch, source_calls).run_once()
    assert source_result["assetId"] == source_id, source_result
    assert source_result["status"] == "ready", source_result
    assert service.catalog.analysis_status(source_id)["status"] == "ready"
    # Identical previews were stored, so the pair is a verified near-duplicate.
    assert (
        service.catalog.get_fingerprint(source_id, BURST_HASH_VERSION) is not None
    ), "the source's own analysis must persist its fingerprint"
    # Put the target back in the queue; its preview is cached so no
    # regeneration is expected, and the evicted source is now its only
    # candidate.
    service.catalog.queue_ai([target_id])

    # Evict the source's preview (an eviction-shaped miss), then run the
    # target's analysis.
    capsys.readouterr()  # discard setup chatter
    wipe_cache_dir(backend, source_id)
    target_calls = [0]
    target_result = make_worker(backend, monkeypatch, target_calls).run_once()

    # The target's own preview was never evicted, so it is reused as-is...
    assert target_result["assetId"] == target_id, target_result
    assert target_result["status"] == "ready", target_result
    assert target_result.get("previewRegenerated") is None
    # ...and it was computed by the VLM, because the only candidate was
    # evicted and therefore skipped, not reused.
    assert target_result["semanticOrigin"] == "computed"
    assert "reuseMatch" not in target_result
    assert target_calls[0] == 1
    # The miss is observable in the operational log.
    logged = capsys.readouterr().out
    assert '"status": "reuse_candidate_skipped"' in logged.replace("\n", " ")
    assert f'"assetId": "{source_id}"' in logged.replace("\n", " ")
    # The source is skipped, not broken: its evicted preview was NOT recreated,
    # and the target's analysis published fine against the real tables.
    assert not cache_paths(service, service.catalog.get(source_id))["preview"].exists()
    with service.catalog.engine.connect() as t:
        run = t.execute(
            text(
                "SELECT semantic_origin, reuse_policy_version FROM analysis_runs "
                "WHERE asset_id = :a AND is_current = true"
            ),
            {"a": target_id},
        ).one()
    assert run[0] == "computed" and run[1] is None


# --- Phase 2B: the worker driving the real RemoteFaceAnalyzer. --------------

STUB_FACE = {"box": [0.1, 0.1, 0.2, 0.2], "confidence": 0.9, "embedding": [1.0, 0.0]}

STUB_HEALTH = {
    "status": "ok",
    "models": {
        "faceDetector": "yunet-2023mar",
        "faceEmbedding": {
            "name": ADAFACE_IDENTITY["name"],
            "revision": ADAFACE_IDENTITY["revision"],
            "weightsSha256": ADAFACE_IDENTITY["weights_sha256"],
            "runtime": "onnxruntime-1.23.2",
        },
    },
    "detectionThreshold": 0.8,
    "concurrency": 1,
    "inFlight": 0,
    "queueDepth": 0,
}


@dataclass
class _CapturedRequest:
    method: str
    path: str
    headers: object
    body: bytes


class _FaceServiceStub:
    """In-process stand-in for the face-service's HTTP contract: ``GET
    /health`` (verified identity) and ``POST /v1/faces/analyze`` (raw JPEG
    in, face list out) over a real 127.0.0.1 socket, so the worker's
    ``RemoteFaceAnalyzer`` runs its real httpx path end to end. No external
    service is started. Both endpoints answer a configurable status so
    Phase 3A tests can take the service down (503) at the gate or mid-job."""

    def __init__(self, health_status: int = 200, analyze_status: int = 200):
        self.requests: list[_CapturedRequest] = []
        self.health_status = health_status
        self.analyze_status = analyze_status
        stub = self

        class Handler(BaseHTTPRequestHandler):
            def log_message(self, *args):
                pass

            def _send(self, status: int, payload: dict):
                body = json.dumps(payload).encode()
                self.send_response(status)
                self.send_header("Content-Type", "application/json")
                self.send_header("Content-Length", str(len(body)))
                self.end_headers()
                self.wfile.write(body)

            def do_GET(self):
                stub.requests.append(_CapturedRequest("GET", self.path, self.headers, b""))
                self._send(stub.health_status, STUB_HEALTH)

            def do_POST(self):
                body = self.rfile.read(int(self.headers["Content-Length"]))
                stub.requests.append(_CapturedRequest("POST", self.path, self.headers, body))
                self._send(stub.analyze_status, {"schemaVersion": 1, "faces": [STUB_FACE]})

        self._server = ThreadingHTTPServer(("127.0.0.1", 0), Handler)
        self.port = self._server.server_address[1]
        threading.Thread(target=self._server.serve_forever, daemon=True).start()

    def stop(self):
        self._server.shutdown()
        self._server.server_close()


def test_worker_runs_face_stage_through_remote_service(backend, monkeypatch):
    """Phase 2B: ``_faces`` is the real ``RemoteFaceAnalyzer`` (no stub for
    the client itself) pointed at a stub HTTP server implementing the
    face-service contract: the worker sends its prepared JPEG over real
    HTTP and the artifact records the verified remote identity."""
    stub = _FaceServiceStub()
    try:
        backend.service.settings = backend.service.settings.model_copy(
            update={
                # The VLM URL just needs to be non-empty (configured); its
                # probe is stubbed, so the gate passes on the real face probe.
                "ai_base_url": "http://vlm-stub/v1",
                "face_service_url": f"http://127.0.0.1:{stub.port}",
                "face_service_token": "tok-test",
            }
        )
        calls = [0]

        def fake_analyze_semantics(settings, jpeg):
            calls[0] += 1
            return FAKE_SEMANTIC, DIGEST, {}

        monkeypatch.setattr(ai_worker, "analyze_semantics", fake_analyze_semantics)
        monkeypatch.setattr(ai_worker, "resolve_model_digest", lambda settings, model: DIGEST)

        worker = AIWorker(backend.service)
        assert isinstance(worker.faces, RemoteFaceAnalyzer)
        monkeypatch.setattr(worker, "_probe_vlm", lambda: True)
        asset_id = add_plain_asset(backend, "remote-faces.JPG")
        make_preview(backend, asset_id)

        result = worker.run_once()
        assert result["status"] == "ready", result
        assert result["semanticOrigin"] == "computed"
        assert result["counters"]["stageFailures"]["face"] == 0
        assert calls[0] == 1

        # The stub saw the gate's identity probe (Phase 3A), the analyze
        # preflight probe, and the raw JPEG, all bearer-authenticated.
        healths = [r for r in stub.requests if r.path == "/health"]
        analyzes = [r for r in stub.requests if r.path == "/v1/faces/analyze"]
        assert len(healths) == 2 and len(analyzes) == 1
        assert all(r.method == "GET" for r in healths)
        assert (analyzes[0].method, analyzes[0].path) == ("POST", "/v1/faces/analyze")
        for request in stub.requests:
            assert request.headers.get("Authorization") == "Bearer tok-test"
        assert analyzes[0].headers.get("Content-Type") == "image/jpeg"
        assert analyzes[0].body[:2] == b"\xff\xd8"  # the worker's real prepare_jpeg output

        # The artifact records the identity verified from the remote health.
        artifact = backend.service.storage.get_json(
            f"analysis/{asset_id}/{PIPELINE_VERSION}/{result['runId']}.json"
        )
        assert artifact["models"]["faceDetector"] == "yunet-2023mar"
        assert artifact["models"]["faceEmbedding"] == {
            **ADAFACE_IDENTITY,
            "runtime": "onnxruntime-1.23.2",
        }
        assert artifact["faces"] == [STUB_FACE]
    finally:
        stub.stop()


# --- Phase 3A: the service gate, requeue, and the bounded dispatcher. ------


def ai_job_row(backend, asset_id: str) -> dict:
    """The raw ai-v1 job row (status / attempts / error) as stored."""
    with backend.service.catalog.engine.connect() as connection:
        row = connection.execute(
            text(
                "SELECT status, attempts, error FROM jobs "
                "WHERE asset_id = :a AND job_type = 'ai-v1'"
            ),
            {"a": asset_id},
        ).tuples().one()
    return {"status": row[0], "attempts": row[1], "error": row[2]}


def test_unconfigured_never_claims(backend):
    """AI not configured (a service URL empty): ``run_once`` never claims —
    the job row stays ``pending`` with attempts 0 and the result reports the
    idle reason, so the backlog accumulates instead of failing."""
    asset_id = add_plain_asset(backend, "unconfigured.JPG")
    make_preview(backend, asset_id)

    backend.service.settings = backend.service.settings.model_copy(
        update={"ai_base_url": "", "face_service_url": ""}
    )
    worker = AIWorker(backend.service)
    assert worker.run_once() == {"status": "idle", "reason": "ai-not-configured"}
    assert ai_job_row(backend, asset_id) == {"status": "pending", "attempts": 0, "error": None}

    # One empty URL is enough (a job always runs both stages).
    asset_id = add_plain_asset(backend, "unconfigured-face.JPG")
    make_preview(backend, asset_id)
    backend.service.settings = backend.service.settings.model_copy(
        update={"ai_base_url": "http://vlm-stub/v1", "face_service_url": ""}
    )
    assert worker.run_once() == {"status": "idle", "reason": "ai-not-configured"}
    assert ai_job_row(backend, asset_id) == {"status": "pending", "attempts": 0, "error": None}


def test_gate_blocks_claim_then_claims_after_recovery(backend, monkeypatch):
    """Configured, but the face-service answers 503 to ``/health`` at the
    gate: no claim, the job row is untouched; the service recovers, the 30 s
    probe cache is reset, and the same pending job is claimed and completes."""
    stub = _FaceServiceStub(health_status=503)
    try:
        backend.service.settings = backend.service.settings.model_copy(
            update={
                "ai_base_url": "http://vlm-stub/v1",
                "face_service_url": f"http://127.0.0.1:{stub.port}",
                "face_service_token": "tok-test",
            }
        )
        worker = AIWorker(backend.service)
        monkeypatch.setattr(worker, "_probe_vlm", lambda: True)
        calls = [0]

        def fake_analyze_semantics(settings, jpeg):
            calls[0] += 1
            return FAKE_SEMANTIC, DIGEST, {}

        monkeypatch.setattr(ai_worker, "analyze_semantics", fake_analyze_semantics)
        monkeypatch.setattr(ai_worker, "resolve_model_digest", lambda settings, model: DIGEST)

        asset_id = add_plain_asset(backend, "gate-down.JPG")
        make_preview(backend, asset_id)

        # Down at the gate: no claim, the job row is untouched.
        assert worker.run_once() == {"status": "idle", "reason": "face-service-unavailable"}
        assert ai_job_row(backend, asset_id) == {
            "status": "pending",
            "attempts": 0,
            "error": None,
        }
        assert calls[0] == 0

        # The service recovers; reset the 30 s probe cache and run again.
        stub.health_status = 200
        worker._probe_cache = None
        result = worker.run_once()
        assert result["status"] == "ready", result
        assert result["assetId"] == asset_id
        assert result["counters"]["stageFailures"]["face"] == 0
        assert calls[0] == 1
    finally:
        stub.stop()


def test_face_outage_mid_job_requeues_then_completes(backend, monkeypatch):
    """The face-service is healthy at the gate (the job is claimed) but its
    analyze call answers 503 mid-job — after the fingerprint stage: the job
    goes back to ``pending`` (attempts 1, error recorded, lease cleared) and
    is claimed again, completing, once the service is restored."""
    stub = _FaceServiceStub(analyze_status=503)
    try:
        backend.service.settings = backend.service.settings.model_copy(
            update={
                "ai_base_url": "http://vlm-stub/v1",
                "face_service_url": f"http://127.0.0.1:{stub.port}",
                "face_service_token": "tok-test",
            }
        )
        worker = AIWorker(backend.service)  # the real RemoteFaceAnalyzer
        monkeypatch.setattr(worker, "_probe_vlm", lambda: True)
        calls = [0]

        def fake_analyze_semantics(settings, jpeg):
            calls[0] += 1
            return FAKE_SEMANTIC, DIGEST, {}

        monkeypatch.setattr(ai_worker, "analyze_semantics", fake_analyze_semantics)
        monkeypatch.setattr(ai_worker, "resolve_model_digest", lambda settings, model: DIGEST)

        asset_id = add_plain_asset(backend, "mid-job-outage.JPG")
        make_preview(backend, asset_id)

        # Healthy at the gate (200), claimed, then the face stage's analyze
        # call dies: service-unavailable class -> requeued, not failed.
        result = worker.run_once()
        assert result["status"] == "requeued", result
        assert result["reason"] == "service-unavailable"
        assert result["stage"] == "face"
        assert "503" in result["error"]
        assert result["counters"]["stageFailures"]["face"] == 1
        assert calls[0] == 0  # the VLM was never invoked
        assert ai_job_row(backend, asset_id) == {
            "status": "pending",
            "attempts": 1,
            "error": result["error"],
        }

        # The service is restored: the same pending job is claimed again and
        # completes — the backlog survives the outage.
        stub.analyze_status = 200
        worker._probe_cache = None
        result = worker.run_once()
        assert result["status"] == "ready", result
        assert result["assetId"] == asset_id
        assert result["semanticOrigin"] == "computed"
        assert calls[0] == 1
        assert ai_job_row(backend, asset_id)["status"] == "ready"
    finally:
        stub.stop()


def test_vlm_request_error_fails_job_not_requeued(backend, monkeypatch):
    """A 4xx from the VLM (e.g. a bad API key) is a request error, not a
    service outage: the job fails with its stage, exactly as before Phase
    3A — it is not requeued (recovery stays the manual requeue)."""
    calls = [0]
    worker = make_worker(backend, monkeypatch, calls)

    def failing_analyze_semantics(settings, jpeg):
        raise AIRequestError("401 Unauthorized: invalid api key")

    monkeypatch.setattr(ai_worker, "analyze_semantics", failing_analyze_semantics)

    asset_id = add_plain_asset(backend, "vlm-4xx.JPG")
    make_preview(backend, asset_id)

    result = worker.run_once()
    assert result["status"] == "failed", result
    assert result["stage"] == "semantic"
    assert "401" in result["error"]
    assert result["counters"]["stageFailures"]["semantic"] == 1
    row = ai_job_row(backend, asset_id)
    assert row["status"] == "failed"
    assert row["attempts"] == 1
    assert "401" in (row["error"] or "")


def test_dispatcher_idles_when_unconfigured(backend, monkeypatch, capsys):
    """The long-running dispatcher with no AI configured: a fixed 10 s
    cadence (no doubling), never a claim, the transition logged once, and
    the slow heartbeat carrying the backlog size."""
    backend.service.settings = backend.service.settings.model_copy(
        update={"ai_base_url": "", "face_service_url": ""}
    )
    asset_id = add_plain_asset(backend, "dispatcher-idle.JPG")
    make_preview(backend, asset_id)

    sleeps: list[float] = []
    monkeypatch.setattr(ai_worker.time, "sleep", lambda seconds: sleeps.append(seconds))

    gate_calls = {"n": 0}
    real_gate = AIWorker._gate

    def gated(self):
        state, detail = real_gate(self)
        gate_calls["n"] += 1
        if gate_calls["n"] >= 4:
            raise ai_worker._StopRunning
        return state, detail

    monkeypatch.setattr(AIWorker, "_gate", gated)

    thread = threading.Thread(target=ai_worker.run, args=(backend.service,), daemon=True)
    thread.start()
    thread.join(timeout=30)
    assert not thread.is_alive()

    assert sleeps == [10, 10, 10]  # fixed cadence, no backoff doubling
    assert ai_job_row(backend, asset_id) == {
        "status": "pending",
        "attempts": 0,
        "error": None,
    }
    out = capsys.readouterr().out
    assert out.count('"state-transition"') == 1
    assert '"previous": null' in out
    assert '"state": "not-configured"' in out
    assert '"status": "heartbeat"' in out
    assert "AI services not configured; 1 analysis jobs waiting" in out


def test_dispatcher_backoff_doubles_when_unhealthy(backend, monkeypatch, capsys):
    """Configured, but the face-service stays 503 at the gate: the
    dispatcher claims nothing and sleeps a 10 s backoff that doubles (10,
    20, 40, ... capped at 120 s), transition-logged once."""
    stub = _FaceServiceStub(health_status=503)
    try:
        backend.service.settings = backend.service.settings.model_copy(
            update={
                "ai_base_url": "http://vlm-stub/v1",
                "face_service_url": f"http://127.0.0.1:{stub.port}",
                "face_service_token": "tok-test",
            }
        )
        asset_id = add_plain_asset(backend, "dispatcher-backoff.JPG")
        make_preview(backend, asset_id)

        sleeps: list[float] = []
        monkeypatch.setattr(ai_worker.time, "sleep", lambda seconds: sleeps.append(seconds))
        monkeypatch.setattr(AIWorker, "_probe_vlm", lambda self: True)

        gate_calls = {"n": 0}
        real_gate = AIWorker._gate

        def gated(self):
            state, detail = real_gate(self)
            gate_calls["n"] += 1
            if gate_calls["n"] >= 4:
                raise ai_worker._StopRunning
            return state, detail

        monkeypatch.setattr(AIWorker, "_gate", gated)

        thread = threading.Thread(target=ai_worker.run, args=(backend.service,), daemon=True)
        thread.start()
        thread.join(timeout=30)
        assert not thread.is_alive()

        assert sleeps == [10, 20, 40]
        assert ai_job_row(backend, asset_id) == {
            "status": "pending",
            "attempts": 0,
            "error": None,
        }
        out = capsys.readouterr().out
        assert out.count('"state-transition"') == 1
        assert '"state": "face-service-unavailable"' in out
    finally:
        stub.stop()
